baseurl = "https://dddpaul.github.io/blog/"
languageCode = "en-us"
title = "Dev notes"
theme = "hyde"
pygmentsuseclasses = true

[params]
    Description = "Notes about Android, Java, JavaScript, Go and other technical stuff"
    disqusShortname = "dddpaul-github"

[Taxonomies]
    tag = "tags"
    series = "series"

[permalinks]
    posts = "/:year/:month/:day/:filename/"

[[menu.main]]
    Name = "Google+"
    Url ="http://google.com/+PavelDerendyaev1"
[[menu.main]]
    name = "GitHub"
    url ="http://github.com/dddpaul"
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
