baseurl = "http://dddpaul.github.io/blog"
languageCode = "en-us"
title = "Dev notes"
theme = "hyde"
pygmentsuseclasses = true

[params]
    Description = "Notes about Android, Java, JavaScript, Go and other technical stuff"
    disqusShortname = "dddpaul-github"
    Path = "/blog" # Comment out to test tags on localhost

[Taxonomies]
    tag = "tags"
    series = "series"

[permalinks]
    posts = "/blog/:year/:month/:day/:filename/"

[[menu.main]]
    Name = "Google+"
    Url ="http://google.com/+PavelDerendyaev1"
[[menu.main]]
    name = "GitHub"
    url ="http://github.com/dddpaul"
[[menu.main]]
    name = "RSS"
    url = "index.xml"
