baseurl = "http://dddpaul.github.io/blog"
languageCode = "en-us"
title = "Dev notes"

[permalinks]
  posts = "blog/:year/:month/:day/:filename/"

[params]
  Description = "Notes about Android, Java, JavaScript, Go and other technical stuff"
  Path = "/blog" # Comment out to test on localhost

[[menu.main]]
    Name = "Google+"
    Url ="http://google.com/+PavelDerendyaev1"
[[menu.main]]
    name = "GitHub"
    url ="http://github.com/dddpaul"
[[menu.main]]
    name = "RSS"
    url = "index.xml"
