baseurl = "https://dddpaul.github.io/blog/"
languageCode = "en-us"
title = "Pavel Derendyaev notes"
theme = "hyde"
pygmentsuseclasses = true

[params]
    Description = " "
    disqusShortname = "dddpaul-github"

[Taxonomies]
    tag = "tags"
    series = "series"

[permalinks]
    posts = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "GitHub"
    url ="http://github.com/dddpaul"
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
